version: '3.8'

services:
  zrp-pokemon-backend:
    image: zrp-pokemon-backend:latest
    build: .
    ports:
      - 3000:3000
    volumes:
      - node_modules_cache:/usr/zrp_pokemon_backend/node_modules
      - ./src:/usr/zrp_pokemon_backend/src
      - ./nest-cli.json:/usr/zrp_pokemon_backend/nest-cli.json
      - ./tsconfig.json:/usr/zrp_pokemon_backend/tsconfig.json
      - ./tsconfig.build.json:/usr/zrp_pokemon_backend/tsconfig.build.json
      - ./package.json:/usr/zrp_pokemon_backend/package.json
      - ./package-lock.json:/usr/zrp_pokemon_backend/package-lock.json
  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/